[build]
  command = "npm run build"
  publish = "dist"
[[redirects]]
  from = "/api/podcast-feed"
  to = "/.netlify/functions/podcast-feed"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
