import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const main=fs.readFileSync(new URL('../src/main.jsx',import.meta.url),'utf8');
const css=fs.readFileSync(new URL('../src/styles.css',import.meta.url),'utf8');
const meta=JSON.parse(fs.readFileSync(new URL('../VERSION.json',import.meta.url),'utf8'));
test('release metadata advances to v1.4.10.43a',()=>{assert.equal(meta.version,'1.4.10.43a');assert.equal(meta.build,'141043A');assert.match(main,/const VERSION='1\.4\.10\.43a'/)});
test('expanded intelligence uses a Daily Decision Brief',()=>{assert.match(main,/function DecisionBrief/);for(const label of ['TOP STORY','TODAY’S OUTLOOK','WATCH TODAY','USE FIRST','Research desk'])assert.match(main,new RegExp(label));});
test('detailed intelligence is preserved under progressive disclosure',()=>{assert.match(main,/brief-legacy/);assert.match(main,/HighestImpactDecisionExperience/);assert.match(main,/DecisionIntelligencePanel/);assert.match(main,/DailyCommandCenter/);});
test('Decision Intelligence is constrained to viewport',()=>{assert.match(css,/v1\.4\.10\.43a — continuous editorial Daily Brief/);assert.match(css,/width:100%;max-width:100%;min-width:0/);assert.match(css,/overflow:hidden/);});
test('new health readings use local current time and reject future defaults',()=>{assert.match(main,/storedDateTimeLocal/);assert.match(main,/New readings cannot be dated in the future/);assert.match(main,/max=\{row\?undefined:toDateTimeLocal\(\)\}/);});
