import fs from 'node:fs';
import assert from 'node:assert/strict';
const main=fs.readFileSync(new URL('../src/main.jsx',import.meta.url),'utf8');
const css=fs.readFileSync(new URL('../src/styles.css',import.meta.url),'utf8');
const version=JSON.parse(fs.readFileSync(new URL('../VERSION.json',import.meta.url),'utf8'));
assert.equal(version.version,'1.4.15.52');
assert.match(main,/placeholder="Search shopping items…"/);
assert.match(main,/shopping-scroll-region/);
assert.match(main,/filteredRows/);
assert.doesNotMatch(main,/className="shopping-retailer-group" key=\{retailer\} open/);
assert.match(main,/shopping-retailer-group builder-category-section/);
assert.match(main,/summary className="builder-category-summary"><b>\{retailer\}<\/b><span>\{items.length\}<\/span>/);
assert.doesNotMatch(main,/summary><Store\/>/);
assert.match(css,/\.shopping-cart-content\.embedded \.shopping-product-card\{[^}]*background:#263a2d/s);
assert.match(css,/\.shopping-cart-content\.embedded \.shopping-retailer-groups\{[^}]*gap:0/s);
assert.match(css,/\.shopping-cart-content\.embedded \.shopping-toolbar\{[^}]*margin:auto 0 0/s);
assert.match(css,/\.shopping-scroll-region\{[^}]*overflow-y:auto/s);
assert.match(main,/version:'1\.4\.15\.52'/);
console.log('v1.4.15.52 focused acceptance: 12\/12 passed');
