import assert from 'node:assert/strict';
import fs from 'node:fs';
const main=fs.readFileSync(new URL('../src/main.jsx',import.meta.url),'utf8');
const css=fs.readFileSync(new URL('../src/styles.css',import.meta.url),'utf8');
const version=JSON.parse(fs.readFileSync(new URL('../VERSION.json',import.meta.url),'utf8'));
assert.match(main,/function ShoppingCartContent\(\{embedded=false\}\)/);
assert.match(main,/<ShoppingCartContent embedded\/>/);
assert.match(main,/shopping-cart-content\$\{embedded\?' embedded':''\}/);
assert.match(main,/Refresh Images/);
assert.match(main,/shopping-retailer-groups/);
assert.match(main,/Shopping Cart content into Library → Shopping/);
assert.doesNotMatch(main,/library-shopping-placeholder/);
assert.match(css,/v1\.4\.15\.51 — Library tabs and Shopping integration/);
assert.match(css,/\.library-folder-tabs button\{[^}]*min-height:58px/);
assert.match(css,/\.food-library-page \.meals-library-head\{[^}]*border-bottom/);
assert.match(css,/\.shopping-cart-content\.embedded/);
assert.equal(version.version,'1.4.15.51');
assert.equal(version.build_id,'141551');
assert.equal(version.release_id,'FH-20260729-141551');
console.log('v1.4.15.51 focused acceptance: 14/14 passed');
