import assert from 'node:assert/strict';
import fs from 'node:fs';
const main=fs.readFileSync(new URL('../src/main.jsx',import.meta.url),'utf8');
const css=fs.readFileSync(new URL('../src/styles.css',import.meta.url),'utf8');
const version=JSON.parse(fs.readFileSync(new URL('../VERSION.json',import.meta.url),'utf8'));
assert.match(main,/<h2>Library<\/h2>/);
assert.match(main,/library-folder-tabs/);
assert.match(main,/<Apple\/><span>Food<\/span>/);
assert.match(main,/<ShoppingCart\/><span>Shopping<\/span>/);
assert.match(main,/library-shopping-placeholder/);
assert.match(main,/Show favorites/);
assert.doesNotMatch(main,/aria-label="Library results"/);
assert.match(main,/Search foods, recipes, and meals/);
assert.match(css,/Library consolidation phase 1/);
assert.equal(version.version,'1.4.15.50');
assert.equal(version.build_id,'141550');
assert.equal(version.release_id,'FH-20260729-141550');
console.log('v1.4.15.50 focused acceptance: 12/12 passed');
