import assert from 'node:assert/strict';
import fs from 'node:fs';
const main=fs.readFileSync('src/main.jsx','utf8');
const css=fs.readFileSync('src/styles.css','utf8');
const version=JSON.parse(fs.readFileSync('VERSION.json','utf8'));
assert.equal(version.version,'1.4.15.53');
assert.match(main,/function SharedFoodLibraryCard/);
assert.doesNotMatch(main,/function ShoppingProductCard/);
assert.match(main,/ShoppingCartContent embedded onOpenItem=/);
assert.match(main,/setRecipeDetail\(\{type:'food',\.\.\.food\}\)/);
assert.match(main,/shopping-shared-card-button/);
assert.match(main,/SharedFoodLibraryCard title=\{item\.item\}/);
assert.match(main,/SharedFoodLibraryCard title=\{entry\.title\}/);
assert.match(css,/shopping-cart-content\.embedded\{padding-left:0;padding-right:0\}/);
assert.match(css,/border-radius:18px!important/);
assert.match(main,/Refresh Images/);
assert.match(main,/Search shopping items…/);
assert.match(main,/Retailer not specified/);
console.log('v1.4.15.53 focused acceptance: 12/12 passed');
