import assert from 'node:assert/strict';
import fs from 'node:fs';
const db=fs.readFileSync('src/database.js','utf8');
const main=fs.readFileSync('src/main.jsx','utf8');
const pkg=JSON.parse(fs.readFileSync('package.json','utf8'));
const version=JSON.parse(fs.readFileSync('VERSION.json','utf8'));
assert.equal(pkg.version,'1.4.16.55');
assert.equal(version.version,'1.4.16.55');
assert.equal(version.schema_version,135);
assert.match(db,/const TARGET_SCHEMA_VERSION=135;/);
assert.match(db,/version:135,name:'Variety Rotation Schema Migration Repair'/);
assert.match(db,/CREATE TABLE IF NOT EXISTS podcast_playlist_variety_rotation/);
assert.match(db,/CREATE INDEX IF NOT EXISTS idx_podcast_playlist_variety_rotation_order/);
assert.match(db,/function ensureVarietyRotationSchema\(\)/);
assert.match(db,/ensureVarietyRotationSchema\(\);\n    reconcileImportSchema/);
assert.match(db,/INSERT OR IGNORE INTO podcast_playlist_variety_rotation[\s\S]*COALESCE\(p\.enforce_variety,0\)=1/);
assert.match(db,/if\(!hasTable\('podcast_playlist_variety_rotation'\)\)throw new Error\('Variety rotation schema invariant failed\.'/);
assert.match(main,/const VERSION='1\.4\.16\.55';/);
assert.match(main,/FH-1655\.1/);
console.log('v1.4.16.55 focused migration acceptance: 13/13 passed');
