const text=(value='')=>String(value).replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,'$1').replace(/<[^>]+>/g,' ').replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/\s+/g,' ').trim();
const tag=(xml,names)=>{for(const name of names){const m=xml.match(new RegExp(`<${name}(?:\\s[^>]*)?>([\\s\\S]*?)<\\/${name}>`,'i'));if(m)return text(m[1])}return ''};
const attr=(xml,name,attribute='url')=>xml.match(new RegExp(`<${name}[^>]*\\s${attribute}=["']([^"']+)["'][^>]*>`,'i'))?.[1]||'';
const duration=value=>{if(!value)return 0;if(/^\d+$/.test(value))return Number(value);const parts=value.split(':').map(Number);return parts.reduce((sum,n)=>sum*60+n,0)};
const normalized=value=>text(value).toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
const safeUrl=value=>{try{const u=new URL(value);if(u.protocol!=='https:')return null;if(/^(localhost|127\.|10\.|192\.168\.|169\.254\.|172\.(1[6-9]|2\d|3[01])\.)/.test(u.hostname))return null;return u}catch{return null}};
async function appleEpisodes(id){if(!id)return [];try{const r=await fetch(`https://itunes.apple.com/lookup?id=${encodeURIComponent(id)}&entity=podcastEpisode&limit=200&country=US`,{headers:{'User-Agent':'FizzHealth/1.4.16.3'}});if(!r.ok)return [];const j=await r.json();return (j.results||[]).filter(x=>x.wrapperType==='podcastEpisode')}catch{return []}}
async function overcastEpisodes(id){if(!id)return [];try{const r=await fetch(`https://overcast.fm/itunes${encodeURIComponent(id)}`,{headers:{'User-Agent':'Mozilla/5.0 FizzHealth/1.4.16.3'}});if(!r.ok)return [];const html=await r.text();const out=[];for(const m of html.matchAll(/<a[^>]+href=["'](\/\+[^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi)){const title=text(m[2]);if(title)out.push({title,url:`https://overcast.fm${m[1]}`})}return out}catch{return []}}
export async function onRequestGet({request}){const input=new URL(request.url),feed=safeUrl(input.searchParams.get('url')),appleId=input.searchParams.get('appleId')||'';if(!feed)return Response.json({error:'A valid public HTTPS RSS feed URL is required.'},{status:400});try{const response=await fetch(feed.toString(),{headers:{'User-Agent':'FizzHealth/1.4.16.3 (+podcast RSS reader)','Accept':'application/rss+xml, application/atom+xml, text/xml, application/xml'}});if(!response.ok)throw new Error(`Feed returned ${response.status}`);const xml=await response.text();if(xml.length>8_000_000)throw new Error('Feed is too large.');const items=[...xml.matchAll(/<item(?:\s[^>]*)?>([\s\S]*?)<\/item>/gi)].map(m=>m[1]);const [apple,overcast]=await Promise.all([appleEpisodes(appleId),overcastEpisodes(appleId)]);const episodes=items.map(item=>{const title=tag(item,['title']),guid=tag(item,['guid','id']),published_at=tag(item,['pubDate','published','updated']),description=tag(item,['content:encoded','description','summary']),enclosure_url=attr(item,'enclosure','url'),artwork_url=attr(item,'itunes:image','href')||attr(item,'media:thumbnail','url')||attr(item,'media:content','url'),duration_seconds=duration(tag(item,['itunes:duration','duration']));const key=normalized(title);const a=apple.find(x=>(guid&&String(x.episodeGuid||'')===guid)||normalized(x.trackName)===key);const o=overcast.find(x=>normalized(x.title)===key||normalized(x.title).includes(key)||key.includes(normalized(x.title)));return {title,guid,published_at,description,duration_seconds,enclosure_url,artwork_url,apple_podcasts_url:a?.trackViewUrl||'',overcast_url:o?.url||''}}).filter(x=>x.title).sort((a,b)=>new Date(b.published_at||0)-new Date(a.published_at||0));return Response.json({episodes},{headers:{'Cache-Control':'public, max-age=300'}})}catch(error){return Response.json({error:error.message||'The podcast feed could not be loaded.'},{status:502})}}
