import {evaluateDecision} from '../decision/engine.js';
const n=value=>Number.isFinite(Number(value))?Number(value):0;
const text=value=>String(value??'').trim();
export function restaurantContext({totals={},targets={}}={}){const target=(key,fallback=0)=>n(targets[key]?.target)||fallback;const max=(key,fallback=null)=>targets[key]?.max==null?(target(key,fallback)||fallback):n(targets[key].max);return {daily:{...totals},targets,remaining:{calories:Math.max(0,target('calories',1700)-n(totals.calories)),protein:Math.max(0,target('protein',120)-n(totals.protein)),fiber:Math.max(0,target('fiber',30)-n(totals.fiber)),saturated_fat:Math.max(0,(max('saturated_fat',15)||15)-n(totals.saturated_fat))}}}
export function confidenceBand(value){const score=Math.max(0,Math.min(1,n(value)));return score>=.85?'High':score>=.6?'Medium':'Low'}
export function explainNutritionConfidence(meal={}){
 const confidence=Math.max(0,Math.min(1,n(meal.confidence)));
 const parseList=value=>{try{const parsed=Array.isArray(value)?value:JSON.parse(value||'[]');return Array.isArray(parsed)?parsed:[]}catch{return []}};
 const verified=parseList(meal.verified_nutrients_json),assumptions=parseList(meal.assumptions_json),positive=parseList(meal.positive_factors_json),negative=parseList(meal.negative_factors_json);
 const basisKey=text(meal.confidence_basis||meal.source).toLowerCase();
 const source=/official|published|manufacturer|restaurant_verified/.test(basisKey)?'Official restaurant nutrition':/photo|visual/.test(basisKey)?'Meal photo and visual estimate':/label/.test(basisKey)?'Nutrition label':/user|confirmed/.test(basisKey)?'User-confirmed information':'Restaurant menu description and AI estimate';
 const all=['calories','protein','carbs','fiber','fat','saturated_fat','sodium'];
 const present=all.filter(key=>meal[key]!=null),verifiedFields=verified.length?verified:source==='Official restaurant nutrition'?present:[];
 const assumedFields=all.filter(key=>present.includes(key)&&!verifiedFields.includes(key));
 const deductions=[];
 if(source!=='Official restaurant nutrition'&&source!=='Nutrition label')deductions.push('No official nutrition information is attached to this item.');
 if(!text(meal.serving_description))deductions.push('Serving size is not confirmed.');
 if(!text(meal.ingredients_json))deductions.push('Ingredients are incomplete or unavailable.');
 if(!text(meal.preparation))deductions.push('Preparation method may vary by visit.');
 if(meal.price==null)deductions.push('Price has not been observed.');
 const improvements=[];
 if(source!=='Official restaurant nutrition'&&source!=='Nutrition label')improvements.push('Add an official menu nutrition source or nutrition label.');
 if(!text(meal.serving_description))improvements.push('Confirm the serving size or portion.');
 if(!text(meal.ingredients_json))improvements.push('Confirm the ingredients and sauces.');
 if(!text(meal.preparation))improvements.push('Confirm oils, butter, dressings, and preparation.');
 const summary=confidence>=.85?'The item identity is strong, but estimated nutrients may still vary with portion and preparation.':confidence>=.6?'The item is probably identified correctly, while several nutrition values still depend on assumptions.':'The estimate has limited supporting evidence and should be reviewed before relying on it.';
 return {score:Math.round(confidence*100),band:confidenceBand(confidence),basis:text(meal.confidence_basis)||source,source,summary,verified:verifiedFields,estimated:assumedFields,assumptions,positive,negative,deductions,improvements};
}
export function buildRestaurantLearning({meals=[],templates=[],events=[]}={}){const counts=new Map(),mods=new Map();for(const meal of meals){const key=meal.restaurant_meal_id||meal.food_name;if(key)counts.set(String(key),(counts.get(String(key))||0)+1);const raw=text(meal.restaurant_modifications);if(raw)for(const part of raw.split(/[,;]+/).map(x=>x.trim()).filter(Boolean))mods.set(part,(mods.get(part)||0)+1)}for(const event of events)if(event.event_type==='modification'&&text(event.event_value))mods.set(event.event_value,(mods.get(event.event_value)||0)+1);return {orderCount:meals.length,favoriteMealIds:[...counts.entries()].sort((a,b)=>b[1]-a[1]).map(([id,count])=>({id,count})),commonModifications:[...mods.entries()].sort((a,b)=>b[1]-a[1]).map(([name,count])=>({name,count})),reusableTemplates:[...templates].sort((a,b)=>n(b.favorite)-n(a.favorite)||n(b.use_count)-n(a.use_count))}}
export function restaurantAnalytics({restaurants=[],meals=[],visits=[]}={}){const map=new Map();for(const restaurant of restaurants)map.set(restaurant.restaurant_id,{restaurant,visits:0,orders:0,calories:0,protein:0,fiber:0,saturated_fat:0});for(const visit of visits){const row=map.get(visit.restaurant_id);if(row)row.visits++}for(const meal of meals){const id=meal.restaurant_id||meal.profile_restaurant_id||meal.restaurant_name;let row=map.get(id);if(!row&&meal.restaurant_name){row={restaurant:{restaurant_id:id,name:meal.restaurant_name,cuisine:meal.cuisine||''},visits:0,orders:0,calories:0,protein:0,fiber:0,saturated_fat:0};map.set(id,row)}if(row){row.orders++;row.calories+=n(meal.calories);row.protein+=n(meal.protein);row.fiber+=n(meal.fiber);row.saturated_fat+=n(meal.saturated_fat)}}const rows=[...map.values()].map(row=>({...row,averageCalories:row.orders?Math.round(row.calories/row.orders):0,averageProtein:row.orders?Math.round(row.protein/row.orders):0,averageFiber:row.orders?Math.round(row.fiber/row.orders):0,averageSaturatedFat:row.orders?Math.round(row.saturated_fat*10/row.orders)/10:0})).sort((a,b)=>(b.orders+b.visits)-(a.orders+a.visits));const cuisines=new Map();for(const row of rows){const c=text(row.restaurant.cuisine)||'Unspecified';cuisines.set(c,(cuisines.get(c)||0)+row.orders+row.visits)}return {totalOrders:rows.reduce((a,r)=>a+r.orders,0),totalVisits:visits.length,restaurants:rows,cuisines:[...cuisines.entries()].sort((a,b)=>b[1]-a[1]).map(([cuisine,count])=>({cuisine,count}))}}
export function rankRestaurantMenu({meals=[],totals={},targets={},learning={},limit=12}={}){const context=restaurantContext({totals,targets}),learned=new Map((learning.favoriteMealIds||[]).map(x=>[String(x.id),n(x.count)]));return meals.map(meal=>{const decision=evaluateDecision('restaurant',{meal,...context}),historyBoost=Math.min(6,learned.get(String(meal.id))||0);return {meal,decision:{...decision,score:Math.max(0,Math.min(100,decision.score+historyBoost)),confidence:explainNutritionConfidence(meal)},historyBoost}}).sort((a,b)=>b.decision.score-a.decision.score||String(a.meal.meal_name).localeCompare(String(b.meal.meal_name))).filter((entry,index)=>limit==null||index<Math.max(1,limit)).map((entry,index)=>({...entry,rank:index+1}))}
export function restaurantProfileSummary({restaurant={},visits=[],meals=[]}={}){const favoriteMeals=meals.filter(row=>Number(row.favorite)===1).map(row=>row.meal_name),cuisine=text(restaurant.cuisine);return {favorite:Number(restaurant.favorite)===1||text(restaurant.status).toLowerCase()==='favorite',cuisine:cuisine||'Not specified',visitCount:visits.length,lastVisit:visits[0]?.visited_at||null,favoriteMeals,metadata:{website:restaurant.website||'',phone:restaurant.phone||'',address:restaurant.address||restaurant.location||''}}}
